services:
  wordpress:
    image: wordpress:6.8.1-php8.1-apache
    ports:
      - 8081:80
    networks:
      - wp_network
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: "mysql"
      WORDPRESS_DB_USER: "${USER}"
      WORDPRESS_DB_PASSWORD: "${PASSWORD}"
      WORDPRESS_DB_NAME: "mydb"
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:9.3.0
    networks:
      - wp_network
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: "mydb"
      MYSQL_USER: "${USER}"
      MYSQL_PASSWORD: "${PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${ROOTPASSWORD}"

volumes:
  wordpress_data:
  mysql_data:

networks:
  wp_network:
